### ISSUE TITLE
setup instructions

### ISSUE THREAD

**Issue by Hans-Maulwurf** [The-Turing-Machine/Clippy#1]
Could someone add some lines of setup instructions?

**Comment by thinker3197** [comment]
Hey @Hans-Maulwurf, sorry to say but this project was part of a hackathon which went pretty well for us. We didn't paid much attention to it(although it's cool, take a look at code) and now it's quite difficult for us to prepare a documentation for this.

Closing issue [#1](https://github.com/The-Turing-Machine/Clippy/issues/1)
